// Pricing packages config — load from admin API later
// PricingSection accepts `packages` prop, so swap this for an API call whenever ready

export const PACKAGES = [
  {
    id: 'basic',
    name: 'Basic',
    subtitle: 'Untuk Investor Pemula',
    price: 'Gratis',
    priceNote: 'selamanya',
    accent: '#64748b',
    popular: false,
    cta: 'Mulai Gratis',
    ctaVariant: 'outline',
    features: [
      { text: 'Portfolio tracker (hingga 5 aset)',   included: true  },
      { text: 'Harga realtime Crypto (BTC, ETH…)',   included: true  },
      { text: 'Market Overview — Crypto tab',         included: true  },
      { text: 'Fear & Greed Index',                   included: true  },
      { text: 'Berita pasar (terbatas)',              included: true  },
      { text: 'Derivatives & Open Interest',          included: false },
      { text: 'Whale Alerts Feed',                    included: false },
      { text: 'Token Unlocks Calendar',               included: false },
      { text: 'AI Financial Consultant',              included: false },
      { text: 'Multi-Chart Analysis',                 included: false },
    ],
  },
  {
    id: 'advanced',
    name: 'Advanced',
    subtitle: 'Untuk Trader Aktif',
    price: 'Rp 99.000',
    priceNote: 'per bulan',
    accent: '#F3BA2F',
    popular: true,
    cta: 'Pilih Advanced',
    ctaVariant: 'primary',
    features: [
      { text: 'Portfolio tracker (aset tak terbatas)', included: true  },
      { text: 'Harga realtime semua aset',             included: true  },
      { text: 'Market Overview — semua sektor',        included: true  },
      { text: 'Fear & Greed + Altseason Index',        included: true  },
      { text: 'Berita pasar penuh',                    included: true  },
      { text: 'Derivatives & Open Interest',           included: true  },
      { text: 'Whale Alerts Feed',                     included: true  },
      { text: 'Token Unlocks Calendar',                included: true  },
      { text: 'AI Financial Consultant',               included: false },
      { text: 'Multi-Chart Analysis',                  included: false },
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    subtitle: 'Untuk Institusi & Whale',
    price: 'Rp 299.000',
    priceNote: 'per bulan',
    accent: '#a78bfa',
    popular: false,
    cta: 'Pilih Pro',
    ctaVariant: 'purple',
    features: [
      { text: 'Semua fitur Advanced',                  included: true },
      { text: 'AI Consultant (unlimited chat)',         included: true },
      { text: 'Multi-Chart Analysis',                  included: true },
      { text: 'Stablecoin Flow Tracker',               included: true },
      { text: 'Liquidation Heatmap Advanced',          included: true },
      { text: 'Export data CSV / PDF',                 included: true },
      { text: 'Priority Support',                      included: true },
      { text: 'Early Access — fitur baru',             included: true },
      { text: 'API Access (coming soon)',               included: true },
      { text: 'Custom Alerts & Webhooks',              included: true },
    ],
  },
];
